### PR TITLE
Add the Vault rbw client script

### PR DESCRIPTION
**Pull request by DragoonAethis**
This PR adds a new helper script to fetch Vault credentials from the [rbw](https://github.com/doy/rbw), an alternative and much more lightweight Bitwarden client. The script can be configured with environment variables if needed, but ships with sensible defaults.

### CODE REVIEW

**Comment by felixfontein** [comment]
Thanks for your contribution! Please note that linting currently fails.

**Comment by felixfontein** [comment]
If nobody objects I'll merge this in a few days.

**Comment by felixfontein** [comment]
@DragoonAethis thanks for your contribution!

**Comment by DragoonAethis** [comment]
@felixfontein Thanks for the review and merging :)

**Pull request merged**
